FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt-get install -y --no-install-recommends \
    python \
    python-pip \
    git \
    curl \
    ansible \
    &&  pip install --no-cache-dir pywinrm ansible-lint \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

CMD ["/bin/bash"]
